### PR TITLE
Delete Manifest.toml

### PR DESCRIPTION
**Pull request by eahenle**
Deletes Manifest.toml and adds it to the .gitignore (reduces need to `Pkg.resolve`, especially in Pluto notebooks)

### CODE REVIEW

**Comment by mojaie** [comment]
Thank you very much!
I'm not familiar with Pluto, but is it a significant inconvenience or performance loss? I'd like to keep Manifest.toml as a reference environment for unit test reproducibility.

**Comment by eahenle** [comment]
Eh, it's not a huge deal, so possibly not worth bothering.  But, I think for what you want, you can have  test/Project.toml and test/Manifest.toml, so that when you do `Pkg.test()` it builds according to those.

**Comment by mojaie** [comment]
Yes, it seems much better.

**Comment by eahenle** [comment]
I merged the Project.toml files and moved Manifest.toml into /test

**Comment by mojaie** [comment]
Thank you very much!
CI problem is maybe due to some GitHub action settings. I will fix it someday.

**Pull request merged**
